import 'app_settings.dart';
import 'catalog_source.dart';
import 'practice.dart';

/// Names/frequencies drawn from the Lovable prototype's original Pratiche
/// content, re-sorted into this project's category taxonomy. Evidence
/// level defaults to "nonVerificata" (not individually researched) unless
/// a source below has actually been checked and cited — fasting, sauna/
/// cold-contrast, and cold shower are the exceptions (Moderata, real
/// NIH/PMC sources).
const practiceCatalog = <Practice>[
  // Sonno e recupero
  Practice(
    id: 'sleep-mouth-tape',
    name: 'Tape per la bocca',
    category: PracticeCategory.sonnoRecupero,
    description: 'Un cerotto poroso sulle labbra durante il sonno per incoraggiare la respirazione nasale.',
    goal: 'Respirazione nasale notturna invece che orale.',
    benefits: 'Chi lo usa riporta sonno più silenzioso e meno secchezza delle fauci al risveglio.',
    howToStart: 'Inizia con pochi minuti da svegli per abituarti, poi solo se la respirazione nasale è libera.',
    frequency: 'Ogni notte, gradualmente',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Da evitare in caso di congestione nasale, apnee notturne non diagnosticate o difficoltà respiratorie.',
    tags: ['sonno'],
  ),
  Practice(
    id: 'sleep-room-temp',
    name: 'Temperatura camera 18°C',
    category: PracticeCategory.sonnoRecupero,
    description: 'Mantenere la camera da letto fresca durante la notte.',
    goal: 'Favorire l\'addormentamento tramite il calo naturale della temperatura corporea.',
    benefits: 'Una stanza fresca è tra i fattori ambientali più citati per la qualità del sonno.',
    howToStart: 'Regola il termostato o apri una finestra la sera prima di dormire.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['sonno'],
  ),
  Practice(
    id: 'sleep-early-meal',
    name: 'Ultimo pasto 3h prima del sonno',
    category: PracticeCategory.sonnoRecupero,
    description: 'Lasciare un intervallo tra l\'ultimo pasto e l\'andare a letto.',
    goal: 'Ridurre il carico digestivo durante la notte.',
    benefits: 'Meno reflusso e risvegli notturni per alcune persone.',
    howToStart: 'Sposta gradualmente l\'orario di cena prima, 15 minuti alla volta.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['sonno', 'alimentazione'],
  ),
  Practice(
    id: 'sleep-consistent-schedule',
    name: 'Orari di sonno costanti',
    category: PracticeCategory.sonnoRecupero,
    description: 'Andare a letto e svegliarsi alla stessa ora ogni giorno, weekend inclusi.',
    goal: 'Stabilizzare il ritmo circadiano.',
    benefits: 'La regolarità è uno dei fattori più consistentemente associati a un sonno di qualità.',
    howToStart: 'Fissa un orario di sveglia fisso per primo — l\'orario di addormentamento si regola da sé.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['sonno'],
  ),
  Practice(
    id: 'sleep-log',
    name: 'Registro di orari letto/sveglia',
    category: PracticeCategory.sonnoRecupero,
    description: 'Annotare ogni giorno a che ora vai a letto e ti svegli.',
    goal: 'Avere dati reali sulla tua regolarità, non solo impressioni.',
    benefits: 'Rende visibili pattern che altrimenti passerebbero inosservati.',
    howToStart: 'Usa la card Sonno in Oggi, oppure importa da Salute se già tracciato.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['sonno'],
  ),

  // Respirazione
  Practice(
    id: 'breath-478',
    name: 'Respirazione 4-7-8',
    category: PracticeCategory.respirazione,
    description: 'Inspira 4 secondi, trattieni 7, espira 8.',
    goal: 'Attivare il sistema nervoso parasimpatico prima di dormire.',
    benefits: 'Tecnica di rilassamento semplice, spesso usata per favorire l\'addormentamento.',
    howToStart: 'Prova 4 cicli seduto sul letto, prima di spegnere la luce.',
    frequency: 'Prima di dormire · 4 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['stress', 'sonno'],
  ),
  Practice(
    id: 'breath-vagus',
    name: 'Stimolazione del nervo vago',
    category: PracticeCategory.respirazione,
    description: 'Massaggio leggero dietro l\'orecchio o respirazione lenta per stimolare il nervo vago.',
    goal: 'Favorire una risposta di rilassamento rapida.',
    benefits: 'Riportato come utile per calmare l\'attivazione acuta da stress.',
    howToStart: 'Usa al bisogno, in momenti di tensione.',
    frequency: 'Al bisogno · 2 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['stress'],
  ),

  // Meditazione e gestione dello stress
  Practice(
    id: 'stress-silence',
    name: 'Silenzio intenzionale',
    category: PracticeCategory.meditazioneStress,
    description: 'Alcuni minuti al giorno senza musica, notifiche o conversazioni.',
    goal: 'Dare al sistema nervoso una pausa dallo stimolo costante.',
    benefits: 'Spesso riportato come utile per il recupero mentale nel corso della giornata.',
    howToStart: 'Inizia con 5 minuti, anche solo seduto senza telefono.',
    frequency: 'Quotidiano · 5 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['stress'],
  ),
  Practice(
    id: 'stress-sleep-journal',
    name: 'Diario di qualità del sonno',
    category: PracticeCategory.meditazioneStress,
    description: 'Annotare ogni mattina non solo le ore dormite ma come ci si sente.',
    goal: 'Costruire consapevolezza oltre il semplice dato numerico.',
    benefits: 'Aiuta a collegare abitudini serali a come ti senti il giorno dopo.',
    howToStart: 'Due righe ogni mattina bastano.',
    frequency: 'Ogni mattina · 2 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['sonno', 'stress'],
  ),
  Practice(
    id: 'stress-gratitude',
    name: 'Diario della gratitudine',
    category: PracticeCategory.meditazioneStress,
    description: 'Annotare ogni giorno una o più cose per cui si è grati.',
    goal: 'Spostare l\'attenzione su aspetti positivi della giornata.',
    benefits: 'Tra le pratiche di journaling più studiate per il benessere soggettivo.',
    howToStart: 'Una riga la sera, prima di dormire.',
    frequency: 'Quotidiano · 2 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['stress'],
  ),

  // Movimento e attività fisica
  Practice(
    id: 'move-daily',
    name: 'Movimento quotidiano',
    category: PracticeCategory.movimento,
    description: 'Qualsiasi movimento intenzionale, anche solo camminare.',
    goal: 'Mantenere un livello base di attività ogni giorno.',
    benefits: 'L\'attività fisica regolare è tra gli interventi con evidenza più solida per la salute generale.',
    howToStart: 'Punta a 30 minuti, anche divisi in più momenti.',
    frequency: 'Quotidiano · 30 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['movimento'],
  ),
  Practice(
    id: 'move-cardio-strength',
    name: 'Mix cardio + forza',
    category: PracticeCategory.movimento,
    description: 'Allenamento che combina lavoro cardiovascolare e con i pesi.',
    goal: 'Costruire sia capacità aerobica che massa muscolare.',
    benefits: 'Combinare i due tipi di allenamento copre più aspetti della salute fisica di uno solo.',
    howToStart: 'Due o tre sessioni a settimana, anche brevi, sono un buon punto di partenza.',
    frequency: '4–5 volte a settimana · 45 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['movimento'],
  ),
  Practice(
    id: 'move-mobility',
    name: 'Mobilità e flessibilità',
    category: PracticeCategory.movimento,
    description: 'Esercizi dedicati al range di movimento articolare.',
    goal: 'Mantenere le articolazioni libere e ridurre la rigidità.',
    benefits: 'Utile per chi passa molto tempo seduto o fa allenamenti intensi.',
    howToStart: '10-15 minuti dopo l\'allenamento o al mattino.',
    frequency: '3 volte a settimana · 15 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['movimento', 'recupero'],
  ),
  Practice(
    id: 'move-walk-after-meals',
    name: 'Camminata di 10 min dopo i pasti',
    category: PracticeCategory.movimento,
    description: 'Una breve camminata subito dopo aver mangiato.',
    goal: 'Favorire la gestione della glicemia post-prandiale.',
    benefits: 'Riportato come utile per attenuare i picchi glicemici dopo i pasti.',
    howToStart: 'Anche solo intorno all\'isolato, l\'importante è muoversi.',
    frequency: 'Dopo i pasti · 10 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['movimento', 'alimentazione'],
  ),
  Practice(
    id: 'move-barefoot-walk',
    name: 'Camminata mattutina a piedi nudi',
    category: PracticeCategory.movimento,
    description: 'Camminare a piedi nudi su erba o terra al mattino.',
    goal: 'Unire movimento leggero ed esposizione naturale al mattino.',
    benefits: 'Combina i benefici del camminare con quelli, meno consolidati, del "grounding".',
    howToStart: 'Pochi minuti in giardino o al parco, se disponibile.',
    frequency: 'Quotidiano · 10 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['movimento'],
  ),

  // Esposizione alla luce
  Practice(
    id: 'light-2020-20',
    name: 'Regola 20-20-20 per gli occhi',
    category: PracticeCategory.esposizioneLuce,
    description: 'Ogni 20 minuti al pc, guarda per 20 secondi qualcosa a 20 piedi (~6 metri) di distanza.',
    goal: 'Ridurre l\'affaticamento visivo da schermo.',
    benefits: 'Pratica semplice, raccomandata comunemente da oftalmologi per il lavoro al computer.',
    howToStart: 'Imposta un promemoria ogni 20 minuti durante il lavoro.',
    frequency: 'Durante il lavoro · 1 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['occhi'],
  ),
  Practice(
    id: 'light-no-screens-before-bed',
    name: 'Niente schermi 30 min prima di dormire',
    category: PracticeCategory.esposizioneLuce,
    description: 'Evitare schermi luminosi nella mezz\'ora prima di coricarsi.',
    goal: 'Ridurre l\'esposizione a luce serale che può ritardare il sonno.',
    benefits: 'Riduce uno dei segnali che tengono sveglio il cervello la sera.',
    howToStart: 'Sostituisci con lettura cartacea o un rituale serale senza schermi.',
    frequency: 'Ogni notte · 30 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['sonno', 'luce'],
  ),
  Practice(
    id: 'light-sunset-gazing',
    name: 'Sungazing al tramonto',
    category: PracticeCategory.esposizioneLuce,
    description: 'Osservare la luce del tramonto (mai il sole diretto a mezzogiorno) alla fine della giornata.',
    goal: 'Segnalare al corpo l\'inizio della sera, in modo speculare alla luce del mattino.',
    benefits: 'Estende il principio della luce mattutina alla fine della giornata.',
    howToStart: 'Qualche minuto all\'aperto verso il tramonto, senza fissare il sole quando è alto.',
    frequency: 'Quotidiano · 5 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Non fissare mai il sole quando è alto nel cielo — rischio reale per la retina.',
    tags: ['luce', 'sonno'],
  ),

  // Alimentazione
  Practice(
    id: 'food-cloves-tea',
    name: 'Chiodi di garofano nel tè',
    category: PracticeCategory.alimentazione,
    description: 'Aggiungere chiodi di garofano interi a una tisana o tè.',
    goal: 'Aggiungere polifenoli e varietà aromatica alla dieta.',
    benefits: 'I chiodi di garofano sono tra le spezie con più alta densità di antiossidanti.',
    howToStart: '1-2 chiodi di garofano in infusione per qualche minuto.',
    frequency: 'Quotidiano · 5 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-matcha',
    name: 'Matcha al posto del caffè',
    category: PracticeCategory.alimentazione,
    description: 'Sostituire (in parte) il caffè con il tè matcha.',
    goal: 'Un profilo di caffeina più graduale, con L-teanina.',
    benefits: 'Riportata minore "picco e crollo" rispetto al caffè da chi lo usa regolarmente.',
    howToStart: 'Prova a sostituire una delle tazze di caffè giornaliere.',
    frequency: 'Quotidiano · 4 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione', 'energia'],
  ),
  Practice(
    id: 'food-golden-milk',
    name: 'Golden milk (con pepe nero)',
    category: PracticeCategory.alimentazione,
    description: 'Latte caldo con curcuma, pepe nero e miele.',
    goal: 'Rituale serale caldo con curcumina più biodisponibile grazie alla piperina.',
    benefits: 'La combinazione curcuma+pepe nero ha una base scientifica reale sull\'assorbimento (vedi Curcumina in Lab).',
    howToStart: 'Scalda il latte (anche vegetale), aggiungi un cucchiaino di curcuma e una macinata di pepe nero.',
    frequency: 'Sera · 6 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione', 'sonno'],
  ),
  Practice(
    id: 'food-acv',
    name: 'Aceto di mele prima dei pasti',
    category: PracticeCategory.alimentazione,
    description: 'Un cucchiaio di aceto di mele diluito in acqua prima dei pasti principali.',
    goal: 'Attenuare la risposta glicemica post-prandiale.',
    benefits: 'Alcuni studi mostrano un effetto modesto sulla glicemia post-pasto.',
    howToStart: 'Diluisci sempre in acqua — mai puro, è molto acido per i denti e l\'esofago.',
    frequency: 'Prima dei pasti principali · 1 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    risks: 'Diluire sempre; evitare in caso di reflusso o problemi allo smalto dentale.',
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-kefir',
    name: 'Kefir',
    category: PracticeCategory.alimentazione,
    description: 'Latte fermentato ricco di ceppi probiotici vivi.',
    goal: 'Sostenere la diversità del microbioma intestinale.',
    benefits: 'Uno degli alimenti fermentati più studiati per l\'effetto sul microbioma.',
    howToStart: 'Inizia con piccole quantità se non sei abituato ai fermentati.',
    frequency: 'Quotidiano · 2 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione', 'microbioma'],
  ),
  Practice(
    id: 'food-whole-foods',
    name: 'Cibo integrale, poco processato',
    category: PracticeCategory.alimentazione,
    description: 'Privilegiare alimenti il più vicino possibile alla loro forma naturale.',
    goal: 'Ridurre l\'assunzione di ultra-processati.',
    benefits: 'Tra i pattern alimentari con evidenza più consistente in letteratura nutrizionale.',
    howToStart: 'Un pasto alla volta: sostituisci un prodotto confezionato con l\'equivalente non processato.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['alimentazione'],
  ),

  // Digiuno
  Practice(
    id: 'fasting',
    name: 'Digiuno intermittente 16:8',
    category: PracticeCategory.digiuno,
    description: 'Mangi in una finestra di 8 ore, digiuni per le restanti 16.',
    goal: 'Restringere la finestra alimentare giornaliera.',
    benefits: 'Benefici modesti ma reali su peso, massa grassa e alcuni marcatori glicemici — vedi fonti.',
    howToStart: 'Segna il primo e ultimo pasto della giornata nella sua scheda dedicata.',
    frequency: 'Finestra quotidiana',
    evidenceLevel: EvidenceLevel.moderata,
    approachAffinity: [WellnessApproach.scientific],
    sources: [
      CatalogSource(
        title: 'Research on intermittent fasting shows health benefits (National Institute on Aging — NIH)',
        url: 'https://www.nia.nih.gov/news/research-intermittent-fasting-shows-health-benefits',
      ),
      CatalogSource(
        title: 'Is time-restricted eating (8/16) beneficial for body weight and metabolism? Meta-analysis of RCTs (NIH/PMC)',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10002957/',
        note: 'Benefici reali ma modesti, soprattutto in adulti in sovrappeso — non un intervento provato o universale.',
      ),
    ],
    risks: 'Da valutare con un medico in caso di gravidanza, storia di disturbi alimentari, diabete in terapia farmacologica.',
    tags: ['digiuno', 'alimentazione'],
    linksToFastingDetail: true,
  ),
  Practice(
    id: 'fasting-tre',
    name: 'Alimentazione a tempo ristretto',
    category: PracticeCategory.digiuno,
    description: 'Versione più flessibile del digiuno: una finestra alimentare ampia (es. 10-12 ore), non necessariamente 16:8.',
    goal: 'Un primo passo più graduale verso il digiuno intermittente.',
    benefits: 'Stessa logica del 16:8 ma con una restrizione più lieve.',
    howToStart: 'Inizia restringendo la finestra di un\'ora rispetto alle tue abitudini attuali.',
    frequency: 'Quasi tutti i giorni',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['digiuno', 'alimentazione'],
  ),

  // Recupero
  Practice(
    id: 'recovery-post-workout',
    name: 'Recupero post-workout',
    category: PracticeCategory.recupero,
    description: 'Routine dedicata dopo l\'allenamento: stretching, idratazione, alimentazione mirata.',
    goal: 'Favorire il recupero muscolare e ridurre l\'indolenzimento.',
    benefits: 'Un recupero strutturato è associato a minor rischio di infortunio nel tempo.',
    howToStart: '10-15 minuti subito dopo l\'allenamento.',
    frequency: 'Dopo l\'allenamento · 15 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['recupero', 'movimento'],
  ),
  Practice(
    id: 'recovery-sauna-contrast',
    name: 'Sauna e contrasto caldo-freddo',
    category: PracticeCategory.recupero,
    description: 'Alternare calore (sauna) e freddo (doccia fredda o bagno ghiacciato).',
    goal: 'Stimolare circolazione e recupero tramite lo shock termico.',
    benefits: 'Effetti fisiologici reali su circolazione e sistema nervoso, documentati per la componente fredda.',
    howToStart: 'Inizia con contrasti brevi e moderati, senza esagerare con le temperature estreme.',
    frequency: '2–3 volte a settimana · 30 min',
    evidenceLevel: EvidenceLevel.moderata,
    approachAffinity: [WellnessApproach.scientific],
    sources: [
      CatalogSource(
        title: 'Cold-Water Face Immersion Elicits Cardiac Parasympathetic Activity (J-Stage)',
        url: 'https://www.jstage.jst.go.jp/article/circj/70/6/70_6_773/_article',
        note: 'Effetti fisiologici reali (vasocostrizione, attivazione parasimpatica) ma di breve durata.',
      ),
    ],
    risks: 'Sconsigliato in caso di patologie cardiovascolari non controllate — consulta un medico prima di iniziare.',
    tags: ['recupero'],
  ),
  Practice(
    id: 'recovery-cold-shower',
    name: 'Doccia fredda — ultimi 30 sec',
    category: PracticeCategory.recupero,
    description: 'Chiudere la doccia con 30 secondi di acqua fredda (intorno ai 14°C).',
    goal: 'Stimolo di circolazione e allerta tramite l\'esposizione al freddo.',
    benefits: 'Effetti fisiologici misurabili su circolazione e sistema nervoso parasimpatico.',
    howToStart: 'Riduci gradualmente la temperatura negli ultimi secondi della doccia normale.',
    frequency: 'Quotidiano · 1 min',
    evidenceLevel: EvidenceLevel.moderata,
    approachAffinity: [WellnessApproach.scientific],
    sources: [
      CatalogSource(
        title: 'Face cooling increases cerebral blood flow (NIH/PMC)',
        url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3429079/',
        note: 'Effetti fisiologici reali ma di breve durata — nessuna prova di beneficio duraturo.',
      ),
    ],
    tags: ['recupero'],
  ),
  Practice(
    id: 'recovery-plantar-massage',
    name: 'Auto-massaggio plantare con pallina',
    category: PracticeCategory.recupero,
    description: 'Far rotolare una pallina rigida sotto la pianta del piede.',
    goal: 'Rilassare la fascia plantare e i muscoli del piede.',
    benefits: 'Pratica semplice per chi sta molto in piedi o cammina molto.',
    howToStart: '5 minuti alla sera, alternando i due piedi.',
    frequency: 'Quotidiano · 5 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero'],
  ),

  // Altre pratiche di benessere
  Practice(
    id: 'other-oil-pulling',
    name: 'Oil pulling',
    category: PracticeCategory.altro,
    description: 'Sciacquo orale con olio (es. cocco) per alcuni minuti, poi si sputa.',
    goal: 'Igiene orale complementare, tradizionalmente ayurvedica.',
    benefits: 'Riportato per una sensazione di pulizia orale; evidenza clinica ancora limitata.',
    howToStart: 'Un cucchiaio d\'olio, sciacqua per qualche minuto, sputa (mai ingoiare).',
    frequency: '1 settimana ogni 2 mesi · 10 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['igiene'],
  ),
  Practice(
    id: 'other-mewing',
    name: 'Mewing (postura della lingua)',
    category: PracticeCategory.altro,
    description: 'Mantenere la lingua appoggiata al palato a riposo.',
    goal: 'Postura orale corretta, spesso discussa online per effetti estetici.',
    benefits: 'Le prove sugli effetti estetici a lungo termine restano deboli e molto dibattute.',
    howToStart: 'Nota semplicemente dove sta la tua lingua a riposo durante la giornata.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['postura'],
  ),
  Practice(
    id: 'other-floss',
    name: 'Filo interdentale',
    category: PracticeCategory.altro,
    description: 'Pulizia interdentale quotidiana con filo o idropulsore.',
    goal: 'Rimuovere placca e residui che lo spazzolino non raggiunge.',
    benefits: 'Raccomandazione odontoiatrica standard, anche se studi di alta qualità sull\'efficacia specifica del filo sono sorprendentemente pochi.',
    howToStart: 'Anche solo la sera, prima di lavare i denti.',
    frequency: 'Quotidiano · 3 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['igiene'],
  ),
  Practice(
    id: 'other-grounding',
    name: 'A piedi nudi sulla terra naturale',
    category: PracticeCategory.altro,
    description: 'Camminare scalzi su erba, terra o sabbia ("grounding").',
    goal: 'Contatto diretto con superfici naturali.',
    benefits: 'Le prove scientifiche sui presunti effetti fisiologici restano preliminari e dibattute.',
    howToStart: 'Qualche minuto quando hai accesso a un prato o una spiaggia.',
    frequency: 'Quotidiano · 5 min',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero'],
  ),
  // Categorie aggiuntive dal catalogo completo (Igiene orale, Pelle e capelli,
  // Monitoraggio e biomarcatori) + voci mancanti in Sonno/Nutrizione/Corpo.
  // Nessuna fonte verificata per queste — nonVerificata di default.
  Practice(
    id: 'sleep-early-bed',
    name: 'Andare a letto presto',
    category: PracticeCategory.sonnoRecupero,
    description: 'Anticipare l\'orario in cui vai a letto rispetto alle tue abitudini attuali.',
    goal: 'Aumentare il tempo totale a disposizione per dormire.',
    benefits: 'Più margine per completare i cicli di sonno prima della sveglia.',
    howToStart: 'Sposta l\'orario di 15 minuti alla volta finché non trovi il tuo equilibrio.',
    frequency: 'Ogni notte',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['sonno'],
  ),
  Practice(
    id: 'sleep-dark-cool',
    name: 'Camera buia e fresca',
    category: PracticeCategory.sonnoRecupero,
    description: 'Tenere la camera da letto buia (tende oscuranti) e fresca durante la notte.',
    goal: 'Ridurre gli stimoli ambientali che disturbano il sonno.',
    benefits: 'Meno risvegli notturni legati a luce e calore.',
    howToStart: 'Tende oscuranti e finestra socchiusa o climatizzatore se serve.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['sonno'],
  ),
  Practice(
    id: 'sleep-cycle-alignment',
    name: 'Allineamento ai cicli del sonno',
    category: PracticeCategory.sonnoRecupero,
    description: 'Pianificare l\'orario di sveglia in modo che cada alla fine di un ciclo di sonno (~90 minuti), non nel mezzo.',
    goal: 'Svegliarsi meno intontito, in una fase di sonno più leggero.',
    benefits: 'Riportato come utile per un risveglio più agevole, a parità di ore dormite.',
    howToStart: 'Calcola a ritroso in blocchi di 90 minuti dall\'orario in cui devi svegliarti.',
    frequency: 'Ogni notte',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['sonno'],
  ),
  Practice(
    id: 'food-blueberries',
    name: 'Mirtilli',
    category: PracticeCategory.alimentazione,
    description: 'Una porzione di mirtilli freschi o surgelati nella giornata.',
    goal: 'Aggiungere antociani e polifenoli alla dieta.',
    benefits: 'Tra i frutti con la più alta densità di antiossidanti misurata.',
    howToStart: 'Una manciata a colazione o come spuntino.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-flaxseed',
    name: 'Semi di lino macinati al momento',
    category: PracticeCategory.alimentazione,
    description: 'Semi di lino macinati poco prima di essere consumati (si ossidano rapidamente interi).',
    goal: 'Fibra e omega-3 vegetali (ALA) nella dieta.',
    benefits: 'Fonte vegetale di acidi grassi omega-3 e lignani.',
    howToStart: 'Macina un cucchiaio e aggiungilo a yogurt o porridge.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-raw-honey',
    name: 'Miele grezzo',
    category: PracticeCategory.alimentazione,
    description: 'Miele non pastorizzato, un cucchiaino al giorno.',
    goal: 'Alternativa meno processata allo zucchero raffinato.',
    benefits: 'Riportato per proprietà antimicrobiche blande; resta comunque uno zucchero.',
    howToStart: 'Sostituisci un cucchiaino di zucchero con miele grezzo.',
    frequency: '1 cucchiaino/giorno',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Non adatto a bambini sotto i 12 mesi (rischio botulismo infantile).',
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-bee-pollen',
    name: 'Polline d\'api',
    category: PracticeCategory.alimentazione,
    description: 'Granuli di polline d\'api, in piccola quantità giornaliera.',
    goal: 'Integrazione alimentare tradizionale di proteine e micronutrienti.',
    benefits: 'Riportato per un apporto vario di nutrienti; le prove cliniche restano deboli.',
    howToStart: 'Inizia con pochissimo per verificare tolleranza — rischio allergico reale.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Rischio di reazioni allergiche, soprattutto se allergico al polline o alle api.',
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-royal-jelly',
    name: 'Pappa reale',
    category: PracticeCategory.alimentazione,
    description: 'Integrazione ciclica di pappa reale.',
    goal: 'Pratica tradizionale di supporto energetico.',
    benefits: 'Uso tradizionale diffuso; evidenza clinica solida ancora limitata.',
    howToStart: 'Cicli brevi secondo le indicazioni del prodotto.',
    frequency: 'A cicli',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Rischio allergico, soprattutto se allergico al polline.',
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-reishi-lions-mane',
    name: 'Reishi + Lion\'s Mane',
    category: PracticeCategory.alimentazione,
    description: 'Funghi funzionali (reishi e criniera di leone) in polvere o estratto.',
    goal: 'Supporto tradizionale a stress e concentrazione.',
    benefits: 'Tra i funghi funzionali più studiati, con risultati preliminari incoraggianti.',
    howToStart: 'Segui il dosaggio indicato sul prodotto, introducendo un fungo alla volta.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-collagen-broth',
    name: 'Brodo di collagene fatto in casa',
    category: PracticeCategory.alimentazione,
    description: 'Brodo lungo da ossa, ricco di collagene naturale.',
    goal: 'Fonte alimentare di collagene e aminoacidi.',
    benefits: 'Alternativa whole-food agli integratori di collagene in polvere.',
    howToStart: 'Cuoci ossa a fuoco basso per diverse ore con un filo di aceto.',
    frequency: '2–3 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-gelatin',
    name: 'Gelatina alimentare',
    category: PracticeCategory.alimentazione,
    description: 'Gelatina alimentare (non da dolci industriali) come fonte di collagene.',
    goal: 'Integrazione alimentare di glicina e collagene.',
    benefits: 'Alternativa economica e whole-food al collagene in polvere.',
    howToStart: 'Aggiungi un cucchiaio di gelatina neutra a bevande calde o yogurt.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-urolithin-a',
    name: 'Urolitina A',
    category: PracticeCategory.alimentazione,
    description: 'Metabolita prodotto dai polifenoli del melograno, anche disponibile come integratore.',
    goal: 'Supporto alla funzione mitocondriale (mitofagia).',
    benefits: 'Area di ricerca emergente sulla salute mitocondriale e muscolare nell\'invecchiamento.',
    howToStart: 'Valuta con un professionista prima di aggiungere un nuovo integratore.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-spirulina',
    name: 'Spirulina',
    category: PracticeCategory.alimentazione,
    description: 'Alga blu-verde in polvere o compresse.',
    goal: 'Fonte concentrata di proteine e micronutrienti vegetali.',
    benefits: 'Tra gli alimenti vegetali più densi di nutrienti per porzione.',
    howToStart: 'Inizia con una piccola dose in un frullato per valutare la tolleranza.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Verifica la qualità/purezza della fonte — rischio di contaminanti in prodotti scadenti.',
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-vitamin-d3-k2',
    name: 'Vitamina D3 + K2',
    category: PracticeCategory.alimentazione,
    description: 'Integrazione combinata di vitamina D3 e K2, spesso in gocce.',
    goal: 'Supporto a metabolismo osseo e livelli di vitamina D, specie con poca esposizione solare.',
    benefits: 'La D3 è tra le carenze più comuni nelle popolazioni con poca luce solare; la K2 supporta la corretta collocazione del calcio.',
    howToStart: 'Fai un dosaggio del sangue prima di iniziare per capire la dose adatta.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-polyphenols',
    name: 'Cibi ricchi di polifenoli',
    category: PracticeCategory.alimentazione,
    description: 'Privilegiare regolarmente alimenti ricchi di polifenoli (bacche, tè verde, olio EVO, cacao amaro).',
    goal: 'Aumentare l\'apporto di composti antiossidanti dalla dieta quotidiana.',
    benefits: 'Pattern alimentare associato a diversi indicatori di salute nella letteratura osservazionale.',
    howToStart: 'Aggiungi una porzione di frutti di bosco o un quadratino di cacao amaro al giorno.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'food-low-gi-meal',
    name: 'Struttura del pasto a basso indice glicemico',
    category: PracticeCategory.alimentazione,
    description: 'Ordinare gli alimenti nel pasto (fibre/proteine prima dei carboidrati) o scegliere versioni a basso indice glicemico.',
    goal: 'Attenuare i picchi glicemici post-prandiali.',
    benefits: 'Riportato come utile per la gestione della glicemia dopo i pasti.',
    howToStart: 'Inizia il pasto con verdure o proteine prima dei carboidrati.',
    frequency: 'Ad ogni pasto',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['alimentazione'],
  ),
  Practice(
    id: 'oral-water-floss',
    name: 'Filo interdentale ad acqua',
    category: PracticeCategory.igieneOrale,
    description: 'Idropulsore orale per la pulizia tra i denti con un getto d\'acqua.',
    goal: 'Alternativa o complemento al filo interdentale tradizionale.',
    benefits: 'Utile per chi ha apparecchi, impianti o difficoltà con il filo classico.',
    howToStart: 'Usa la sera dopo lo spazzolino, partendo da intensità bassa.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['igiene'],
  ),
  Practice(
    id: 'oral-tongue-scraper',
    name: 'Nettalingua',
    category: PracticeCategory.igieneOrale,
    description: 'Raschietto per la lingua usato al mattino.',
    goal: 'Rimuovere il velo batterico sul dorso della lingua.',
    benefits: 'Riportato come utile contro l\'alitosi mattutina.',
    howToStart: 'Passa il nettalingua dal fondo verso la punta, 2-3 volte.',
    frequency: 'Ogni mattina',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['igiene'],
  ),
  Practice(
    id: 'oral-night-guard',
    name: 'Bite notturno',
    category: PracticeCategory.igieneOrale,
    description: 'Bite su misura indossato durante il sonno.',
    goal: 'Proteggere i denti dal digrignamento notturno (bruxismo).',
    benefits: 'Protocollo odontoiatrico standard per chi digrigna i denti di notte.',
    howToStart: 'Richiedi una valutazione e un bite su misura al tuo dentista.',
    frequency: 'Ogni notte',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    risks: 'Un bite non adatto può peggiorare l\'occlusione — va fatto su misura da un professionista.',
    tags: ['igiene', 'sonno'],
  ),
  Practice(
    id: 'oral-low-acid-habits',
    name: 'Abitudini orali a basso pH',
    category: PracticeCategory.igieneOrale,
    description: 'Ridurre la frequenza di bevande/cibi molto acidi e non lavare i denti subito dopo averli consumati.',
    goal: 'Proteggere lo smalto dentale dall\'erosione acida.',
    benefits: 'Raccomandazione odontoiatrica comune per prevenire l\'erosione dello smalto.',
    howToStart: 'Aspetta almeno 30 minuti dopo cibi/bevande acide prima di lavare i denti.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['igiene'],
  ),
  Practice(
    id: 'skin-gentle-cleanse',
    name: 'Detersione delicata',
    category: PracticeCategory.pelleCapelli,
    description: 'Detergente delicato, senza solfati aggressivi, sul viso.',
    goal: 'Pulire la pelle senza comprometterne la barriera cutanea.',
    benefits: 'Riduce il rischio di irritazione rispetto a detergenti aggressivi.',
    howToStart: 'Scegli un detergente senza solfati, applicalo con acqua tiepida non calda.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-brush-after-cleanse',
    name: 'Lavare i denti (dopo la detersione)',
    category: PracticeCategory.pelleCapelli,
    description: 'Sequenziare lo skincare prima dello spazzolino, non dopo.',
    goal: 'Evitare che il dentifricio irriti la pelle appena detersa.',
    benefits: 'Piccolo accorgimento di sequenza riportato in ambito skincare.',
    howToStart: 'Prima detergi il viso, poi lava i denti.',
    frequency: '2 volte al giorno',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['pelle', 'igiene'],
  ),
  Practice(
    id: 'skin-spf',
    name: 'SPF (sempre ultimo step AM)',
    category: PracticeCategory.pelleCapelli,
    description: 'Protezione solare come ultimo passaggio della routine mattutina.',
    goal: 'Proteggere la pelle dai raggi UV, principale causa di invecchiamento cutaneo evitabile.',
    benefits: 'Tra le pratiche skincare con l\'evidenza più solida in assoluto contro fotoinvecchiamento e tumori cutanei.',
    howToStart: 'Applica un SPF 30+ ad ampio spettro ogni mattina, anche in inverno o al chiuso vicino a finestre.',
    frequency: 'Ogni mattina',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-cycling',
    name: 'Skin cycling (protocollo 4 notti)',
    category: PracticeCategory.pelleCapelli,
    description: 'Alternanza programmata di esfoliante, retinoide e due notti di recupero.',
    goal: 'Introdurre attivi potenti riducendo il rischio di irritazione.',
    benefits: 'Protocollo diventato popolare tra i dermatologi per bilanciare efficacia e tollerabilità.',
    howToStart: 'Notte 1 esfoliante, notte 2 retinoide, notti 3-4 solo idratante/recupero.',
    frequency: 'Ripeti ogni 4 notti',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-slugging',
    name: 'Slugging',
    category: PracticeCategory.pelleCapelli,
    description: 'Sigillare l\'idratante notturno con un sottile strato di vaselina.',
    goal: 'Ridurre la perdita d\'acqua transepidermica durante la notte.',
    benefits: 'Riportato come utile per pelli molto secche o disidratate.',
    howToStart: 'Applica per ultimo, in strato sottile, solo su pelle già idratata.',
    frequency: '2–3 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Può ostruire i pori su pelli grasse o acneiche.',
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-glycolic-toner',
    name: 'Tonico all\'acido glicolico',
    category: PracticeCategory.pelleCapelli,
    description: 'Tonico esfoliante con acido glicolico (AHA).',
    goal: 'Esfoliazione chimica per texture e luminosità della pelle.',
    benefits: 'Gli AHA sono tra gli esfolianti chimici con evidenza più consolidata in dermatologia.',
    howToStart: 'Inizia 1 volta a settimana e aumenta gradualmente, sempre con SPF al mattino successivo.',
    frequency: '2–3 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    risks: 'Aumenta la fotosensibilità — SPF obbligatorio il giorno dopo.',
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-cold-spoon',
    name: 'Massaggio con cucchiaio freddo',
    category: PracticeCategory.pelleCapelli,
    description: 'Cucchiai raffreddati in frigo passati sul viso per un effetto decongestionante.',
    goal: 'Ridurre gonfiore e rossore percepiti al mattino.',
    benefits: 'Effetto immediato ma temporaneo su circolazione superficiale e gonfiore.',
    howToStart: 'Tieni due cucchiai in frigo e passali sul viso 1-2 minuti.',
    frequency: 'Al bisogno',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-cork-lip-massage',
    name: 'Massaggio delle labbra con sughero',
    category: PracticeCategory.pelleCapelli,
    description: 'Massaggio esfoliante delle labbra con un tappo di sughero.',
    goal: 'Rimuovere pelle secca dalle labbra delicatamente.',
    benefits: 'Alternativa naturale agli scrub labbra commerciali.',
    howToStart: 'Massaggia delicatamente in cerchio per 30 secondi, poi idrata.',
    frequency: '2 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-no-towel-face',
    name: 'Mai asciugamani sul viso',
    category: PracticeCategory.pelleCapelli,
    description: 'Usare un panno pulito dedicato o carta invece dell\'asciugamano del corpo per il viso.',
    goal: 'Ridurre il contatto della pelle del viso con batteri accumulati sul telo.',
    benefits: 'Gli asciugamani riutilizzati accumulano batteri che possono favorire irritazioni.',
    howToStart: 'Dedica un panno pulito solo al viso e cambialo spesso.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-natural-fiber-bedding',
    name: 'Biancheria e indumenti in fibra naturale',
    category: PracticeCategory.pelleCapelli,
    description: 'Preferire cotone, lino o seta a contatto con pelle e capelli (federe incluse).',
    goal: 'Ridurre attrito e accumulo di umidità/batteri rispetto a fibre sintetiche.',
    benefits: 'Riportato come più delicato per pelle sensibile e capelli, specie le federe in seta.',
    howToStart: 'Inizia sostituendo la federa con una in seta o cotone di alta qualità.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-red-light',
    name: 'Luce rossa / fotobiomodulazione',
    category: PracticeCategory.pelleCapelli,
    description: 'Esposizione della pelle a luce rossa/infrarossa a bassa intensità tramite pannello o maschera dedicata.',
    goal: 'Stimolare la produzione di collagene e ridurre l\'infiammazione cutanea.',
    benefits: 'Area di ricerca in crescita, con risultati preliminari incoraggianti su rughe e guarigione.',
    howToStart: 'Segui i tempi di esposizione indicati dal dispositivo, iniziando da sedute brevi.',
    frequency: '3–5 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-scalp-care',
    name: 'Cura del cuoio capelluto',
    category: PracticeCategory.pelleCapelli,
    description: 'Massaggio o trattamento dedicato al cuoio capelluto.',
    goal: 'Sostenere la circolazione locale e la salute dei follicoli.',
    benefits: 'Riportato come utile per il comfort del cuoio capelluto; le prove sulla crescita dei capelli restano preliminari.',
    howToStart: '5 minuti di massaggio con i polpastrelli durante lo shampoo.',
    frequency: 'Settimanale',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-am-serum-routine',
    name: 'Routine di sieri mattutina',
    category: PracticeCategory.pelleCapelli,
    description: 'Sequenza di sieri mirati la mattina, prima della crema e dell\'SPF.',
    goal: 'Applicare attivi specifici (es. vitamina C) nell\'ordine di viscosità corretto.',
    benefits: 'Consente di combinare più attivi mirati nella stessa routine.',
    howToStart: 'Applica dal più liquido al più denso, aspettando che ogni strato assorba.',
    frequency: 'Ogni mattina',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-pm-serum-routine',
    name: 'Routine di sieri serale',
    category: PracticeCategory.pelleCapelli,
    description: 'Sequenza di sieri mirati la sera, dopo la doppia detersione.',
    goal: 'Sfruttare la notte per attivi rigenerativi (es. retinoidi, peptidi).',
    benefits: 'La pelle è più ricettiva agli attivi durante il ciclo di rigenerazione notturno.',
    howToStart: 'Applica dal più liquido al più denso, retinoide per ultimo se in uso.',
    frequency: 'Ogni sera',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['pelle'],
  ),
  Practice(
    id: 'skin-biomarker-priorities',
    name: 'Priorità pelle guidate da biomarcatori',
    category: PracticeCategory.pelleCapelli,
    description: 'Rivedere ogni trimestre la routine skincare in base a foto/osservazioni proprie nel tempo.',
    goal: 'Adattare la routine invece di seguirla in modo statico e immutato.',
    benefits: 'Permette di correggere rotta se una routine non sta dando i risultati attesi.',
    howToStart: 'Confronta foto/note ogni 3 mesi e aggiusta un solo prodotto alla volta.',
    frequency: 'Revisione trimestrale',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['pelle'],
  ),
  Practice(
    id: 'track-bloodwork',
    name: 'Analisi del sangue',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Pannello di analisi del sangue di base (es. lipidi, glicemia, vitamina D, tiroide).',
    goal: 'Avere dati oggettivi periodici sul proprio stato di salute.',
    benefits: 'Permette di individuare per tempo variazioni che i sintomi da soli non mostrerebbero.',
    howToStart: 'Parla con il tuo medico di un pannello base annuale o semestrale.',
    frequency: '2 volte all\'anno',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio'],
  ),
  Practice(
    id: 'track-body-comp',
    name: 'Composizione corporea',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Misurazione della composizione corporea (es. bioimpedenza o DEXA).',
    goal: 'Seguire i cambiamenti di massa magra/grassa nel tempo, non solo il peso.',
    benefits: 'Dato più informativo del solo peso sulla bilancia.',
    howToStart: 'Ripeti la stessa misurazione, stesso orario e condizioni, ogni trimestre.',
    frequency: 'Ogni trimestre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio'],
  ),
  Practice(
    id: 'track-lean-mass',
    name: 'Massa magra',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Monitoraggio nel tempo della massa magra (muscolo, ossa, organi).',
    goal: 'Verificare che gli allenamenti stiano costruendo/mantenendo massa magra.',
    benefits: 'Indicatore utile per chi allena forza o è in fase di ricomposizione corporea.',
    howToStart: 'Usa lo stesso strumento di misura ogni volta per dati confrontabili.',
    frequency: 'Ogni trimestre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio', 'movimento'],
  ),
  Practice(
    id: 'track-fat-mass',
    name: 'Massa grassa',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Monitoraggio nel tempo della percentuale di massa grassa.',
    goal: 'Seguire i cambiamenti di composizione corporea oltre il peso totale.',
    benefits: 'Più informativo del peso da solo per capire progressi reali.',
    howToStart: 'Misura sempre nelle stesse condizioni (es. a digiuno, stesso orario).',
    frequency: 'Ogni trimestre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio'],
  ),
  Practice(
    id: 'track-resting-hr',
    name: 'Frequenza cardiaca a riposo',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Frequenza cardiaca misurata a riposo, spesso al risveglio.',
    goal: 'Seguire un indicatore semplice di forma cardiovascolare e recupero.',
    benefits: 'Un trend in calo nel tempo è spesso associato a un miglioramento della forma cardiovascolare.',
    howToStart: 'Usa uno smartwatch o app dedicata, misurando sempre in condizioni simili.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio'],
  ),
  Practice(
    id: 'track-sleep-metrics',
    name: 'Metriche del sonno',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Dati oggettivi sul sonno (durata, fasi, risvegli) da wearable o app.',
    goal: 'Confrontare la percezione soggettiva del sonno con dati misurati.',
    benefits: 'Rende visibili pattern che il diario da solo potrebbe non cogliere.',
    howToStart: 'Sincronizza il sonno da Salute nella card Sonno di Oggi.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio', 'sonno'],
  ),
  Practice(
    id: 'track-hrv',
    name: 'HRV (variabilità cardiaca)',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Variabilità della frequenza cardiaca, un indicatore di attivazione del sistema nervoso autonomo.',
    goal: 'Seguire un proxy di recupero e stress accumulato nel tempo.',
    benefits: 'Un trend HRV informativo si costruisce nel tempo, più che dal singolo valore giornaliero.',
    howToStart: 'Misura sempre alla stessa ora (es. al risveglio) per dati confrontabili.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio', 'stress'],
  ),
  Practice(
    id: 'track-weekly-trends',
    name: 'Trend settimanali di salute',
    category: PracticeCategory.monitoraggioBiomarcatori,
    description: 'Revisione settimanale dei propri dati (sonno, movimento, umore) invece del solo dato giornaliero.',
    goal: 'Individuare pattern che un singolo giorno non mostra.',
    benefits: 'I trend settimanali sono più stabili e meno rumorosi dei dati di un giorno isolato.',
    howToStart: 'Dedica 5 minuti alla domenica per rivedere la settimana appena passata.',
    frequency: 'Settimanale',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['monitoraggio'],
  ),
  Practice(
    id: 'body-lymph-drainage',
    name: 'Drenaggio linfatico corpo (gambe → addome → braccia → ascelle)',
    category: PracticeCategory.recupero,
    description: 'Auto-massaggio linfatico del corpo, in sequenza dalle gambe verso i linfonodi.',
    goal: 'Sostenere la circolazione linfatica superficiale.',
    benefits: 'Riportato per una sensazione soggettiva di leggerezza; evidenza clinica sull\'effetto estetico resta debole.',
    howToStart: 'Movimenti leggeri verso il cuore, mai pressione forte diretta sui linfonodi.',
    frequency: '3 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero'],
  ),
  Practice(
    id: 'body-k-tape',
    name: 'Tape kinesiologico fai-da-te',
    category: PracticeCategory.recupero,
    description: 'Applicazione di nastro kinesiologico su aree muscolari specifiche.',
    goal: 'Supporto percepito a muscoli o articolazioni sotto sforzo.',
    benefits: 'Uso diffuso in ambito sportivo; le prove sul beneficio meccanico reale restano miste.',
    howToStart: 'Segui un tutorial per la zona specifica — l\'applicazione conta molto.',
    frequency: 'Al bisogno',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero', 'movimento'],
  ),
  Practice(
    id: 'body-massager-red-light',
    name: 'Massaggiatore + luce rossa (pre-workout)',
    category: PracticeCategory.recupero,
    description: 'Massaggiatore percussivo combinato con luce rossa prima dell\'allenamento.',
    goal: 'Preparare i muscoli e la circolazione prima dello sforzo.',
    benefits: 'Riportato come utile per la sensazione soggettiva di attivazione muscolare pre-workout.',
    howToStart: '5-8 minuti sui gruppi muscolari che allenerai.',
    frequency: 'Pre-allenamento',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    tags: ['recupero', 'movimento'],
  ),
  Practice(
    id: 'body-legs-up-wall',
    name: 'Gambe al muro',
    category: PracticeCategory.recupero,
    description: 'Sdraiarsi con le gambe appoggiate verticalmente al muro per alcuni minuti.',
    goal: 'Favorire il ritorno venoso e il rilassamento del sistema nervoso.',
    benefits: 'Posizione yoga semplice, spesso riportata come rilassante a fine giornata.',
    howToStart: '5-10 minuti la sera, respirando lentamente.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero', 'stress'],
  ),
  Practice(
    id: 'body-stomach-vacuum',
    name: 'Stomach vacuum (a stomaco vuoto)',
    category: PracticeCategory.movimento,
    description: 'Esercizio di contrazione del trasverso dell\'addome, a stomaco vuoto.',
    goal: 'Rinforzare la muscolatura addominale profonda.',
    benefits: 'Esercizio classico per il core profondo, popolare in ambito ginnico.',
    howToStart: 'Espira completamente, contrai l\'addome verso l\'interno, mantieni 10-15 secondi.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    risks: 'Evitare in gravidanza o con problemi addominali/ernie non valutati da un medico.',
    tags: ['movimento'],
  ),
  Practice(
    id: 'body-thermal-shock-legs',
    name: 'Shock termico — gambe',
    category: PracticeCategory.recupero,
    description: 'Alternanza caldo-freddo mirata sulle gambe (es. doccia contrastante).',
    goal: 'Stimolare la circolazione locale nelle gambe.',
    benefits: 'Stessa logica fisiologica del contrasto caldo-freddo generale, applicata localmente.',
    howToStart: 'Alterna 30 secondi caldo e 15 freddo sulle gambe, 3-4 cicli.',
    frequency: '3 volte a settimana',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.scientific],
    risks: 'Sconsigliato con problemi circolatori non controllati — consulta un medico.',
    tags: ['recupero'],
  ),
  Practice(
    id: 'body-sauna-steam-jacuzzi',
    name: 'Sauna + bagno turco + idromassaggio (post-workout)',
    category: PracticeCategory.recupero,
    description: 'Combinazione di sauna, bagno turco e idromassaggio dopo l\'allenamento.',
    goal: 'Favorire il recupero muscolare e il rilassamento post-sforzo.',
    benefits: 'Stessa logica di sauna/contrasto già documentata, qui come combinazione estesa.',
    howToStart: 'Alterna brevi sessioni in ciascuno, idratandoti bene tra una e l\'altra.',
    frequency: 'Post-allenamento',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    risks: 'Sconsigliato in caso di patologie cardiovascolari non controllate.',
    tags: ['recupero'],
  ),
  Practice(
    id: 'body-house-temp',
    name: 'Temperatura casa 18–22°C',
    category: PracticeCategory.sonnoRecupero,
    description: 'Mantenere la temperatura di casa in un range moderato tutto il giorno, non solo in camera da letto.',
    goal: 'Comfort termico generale e minor variazione tra ambienti.',
    benefits: 'Estende alla casa intera il principio già noto per la sola camera da letto.',
    howToStart: 'Imposta il termostato in questo range come default.',
    frequency: 'Sempre',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.balanced],
    tags: ['sonno'],
  ),
  Practice(
    id: 'body-ice-wrists-neck',
    name: 'Ghiaccio su polsi e collo',
    category: PracticeCategory.recupero,
    description: 'Applicare ghiaccio o un impacco freddo su polsi e collo per un raffreddamento rapido.',
    goal: 'Abbassare rapidamente la temperatura corporea percepita.',
    benefits: 'I polsi e il collo sono punti con vasi superficiali, spesso usati per un raffreddamento rapido.',
    howToStart: 'Impacco freddo avvolto in un panno, 1-2 minuti per lato.',
    frequency: 'Al bisogno',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero'],
  ),
  Practice(
    id: 'mind-cold-air-morning',
    name: 'Esposizione all\'aria fredda mattutina',
    category: PracticeCategory.recupero,
    description: 'Uscire all\'aperto al freddo per alcuni minuti al mattino, senza giacca pesante.',
    goal: 'Stimolo di allerta e attivazione tramite l\'esposizione al freddo ambientale.',
    benefits: 'Stessa logica fisiologica del contrasto freddo, qui tramite aria invece che acqua.',
    howToStart: 'Pochi minuti fuori al mattino, vestiti leggeri ma senza esagerare.',
    frequency: 'Quotidiano',
    evidenceLevel: EvidenceLevel.nonVerificata,
    approachAffinity: [WellnessApproach.natural],
    tags: ['recupero'],
  ),
];
